<a href="https://colab.research.google.com/github/avikumart/DA-DS-Questions/blob/main/R_codes/bios_511_R_lang_for_HDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# learning R lang basics for the data science and analysis tasks for the healthcare datasets
paste("hello")

[1] "hello"

In [ ]:
# r lang basics

In [ ]:
234+5

[1] 239

In [ ]:
34^4

[1] 1336336

In [ ]:
3^3

[1] 27

In [ ]:
12+4

[1] 16

In [ ]:
1234-132

[1] 1102

In [ ]:
.Machine$double.exponent

[1] 11

In [ ]:
.Machine$double.digits

[1] 53

In [ ]:
NULL

NULL

In [ ]:
NA

[1] NA

In [ ]:
a <- 1:5
a

[1] 1 2 3 4 5

In [ ]:
str(a)

 int [1:5] 1 2 3 4 5

In [ ]:
# strings in R

In [ ]:
b <- "bios 511"
b

[1] "bios 511"

In [ ]:
  search()

 [1] ".GlobalEnv"        "jupyter:irkernel"  "package:stats"
 [4] "package:graphics"  "package:grDevices" "package:utils"
 [7] "package:datasets"  "package:methods"   "Autoloads"
[10] "package:base"

In [ ]:
installed.packages()

            Package     LibPath                       Version Priority
IRdisplay   IRdisplay   /usr/local/lib/R/site-library 1.1     NA
IRkernel    IRkernel    /usr/local/lib/R/site-library 1.3.2   NA
pbdZMQ      pbdZMQ      /usr/local/lib/R/site-library 0.3-14  NA
repr        repr        /usr/local/lib/R/site-library 1.1.7   NA
askpass     askpass     /usr/lib/R/site-library       1.2.1   NA
backports   backports   /usr/lib/R/site-library       1.5.0   NA
base64enc   base64enc   /usr/lib/R/site-library       0.1-3   NA
bit         bit         /usr/lib/R/site-library       4.6.0   NA
bit64       bit64       /usr/lib/R/site-library       4.6.0-1 NA
blob        blob        /usr/lib/R/site-library       1.2.4   NA
boot        boot        /usr/lib/R/site-library       1.3-31  recommended
brew        brew        /usr/lib/R/site-library       1.0-10  NA
brio        brio        /usr/lib/R/site-library       1.1.5   NA
broom       broom       /usr/lib/R/site-library       1.0.9   NA
bslib       bslib       /usr/lib/R/site-library       0.9.0   NA
cachem      cachem      /usr/lib/R/site-library       1.1.0   NA
callr       callr       /usr/lib/R/site-library       3.7.6   NA
cellranger  cellranger  /usr/lib/R/site-library       1.1.0   NA
class       class       /usr/lib/R/site-library       7.3-23  recommended
cli         cli         /usr/lib/R/site-library       3.6.5   NA
clipr       clipr       /usr/lib/R/site-library       0.8.0   NA
cluster     cluster     /usr/lib/R/site-library       2.1.8.1 recommended
codetools   codetools   /usr/lib/R/site-library       0.2-20  recommended
commonmark  commonmark  /usr/lib/R/site-library       2.0.0   NA
conflicted  conflicted  /usr/lib/R/site-library       1.2.0   NA
cpp11       cpp11       /usr/lib/R/site-library       0.5.2   NA
crayon      crayon      /usr/lib/R/site-library       1.5.3   NA
credentials credentials /usr/lib/R/site-library       2.0.2   NA
curl        curl        /usr/lib/R/site-library       7.0.0   NA
data.table  data.table  /usr/lib/R/site-library       1.17.8  NA
⋮           ⋮           ⋮                             ⋮       ⋮
urlchecker  urlchecker  /usr/lib/R/site-library       1.0.1   NA
usethis     usethis     /usr/lib/R/site-library       3.1.0   NA
utf8        utf8        /usr/lib/R/site-library       1.2.6   NA
uuid        uuid        /usr/lib/R/site-library       1.2-1   NA
vctrs       vctrs       /usr/lib/R/site-library       0.6.5   NA
viridisLite viridisLite /usr/lib/R/site-library       0.4.2   NA
vroom       vroom       /usr/lib/R/site-library       1.6.5   NA
waldo       waldo       /usr/lib/R/site-library       0.6.2   NA
whisker     whisker     /usr/lib/R/site-library       0.4.1   NA
withr       withr       /usr/lib/R/site-library       3.0.2   NA
xfun        xfun        /usr/lib/R/site-library       0.53    NA
xml2        xml2        /usr/lib/R/site-library       1.4.0   NA
xopen       xopen       /usr/lib/R/site-library       1.0.1   NA
xtable      xtable      /usr/lib/R/site-library       1.8-4   NA
yaml        yaml        /usr/lib/R/site-library       2.3.10  NA
zip         zip         /usr/lib/R/site-library       2.3.3   NA
base        base        /usr/lib/R/library            4.5.1   base
compiler    compiler    /usr/lib/R/library            4.5.1   base
datasets    datasets    /usr/lib/R/library            4.5.1   base
graphics    graphics    /usr/lib/R/library            4.5.1   base
grDevices   grDevices   /usr/lib/R/library            4.5.1   base
grid        grid        /usr/lib/R/library            4.5.1   base
methods     methods     /usr/lib/R/library            4.5.1   base
parallel    parallel    /usr/lib/R/library            4.5.1   base
splines     splines     /usr/lib/R/library            4.5.1   base
stats       stats       /usr/lib/R/library            4.5.1   base
stats4      stats4      /usr/lib/R/library            4.5.1   base
tcltk       tcltk       /usr/lib/R/library            4.5.1   base
tools       tools       /usr/lib/R/library            4.5.1   base
utils       utils       /usr/lib/R/library            4.5.1   base
            Depends
IRdisplay   R (>= 3.0.1)
IRkernel    R (>= 3.2.0)
pbdZMQ      R (>= 3.5.0)
repr        R (>= 3.0.1)
askpass     NA
backports   R (>= 3.0.0)
base64enc   R (>= 2.9.0)
bit         R (>= 3.4.0)
bit64       R (>= 3.4.0), bit (>= 4.0.0)
blob        NA
boot        R (>= 3.0.0), graphics, stats
brew        NA
brio        R (>= 3.6)
broom       R (>= 4.1)
bslib       R (>= 2.10)
cachem      NA
callr       R (>= 3.4)
cellranger  R (>= 3.0.0)
class       R (>= 3.0.0), stats, utils
cli         R (>= 3.4)
clipr       NA
cluster     R (>= 3.5.0)
codetools   R (>= 2.1)
commonmark  NA
conflicted  R (>= 3.2)
cpp11       R (>= 4.0.0)
crayon      NA
credentials NA
curl        R (>= 3.0.0)
data.table  R (>= 3.3.0)
⋮           ⋮
urlchecker  R (>= 3.3)
usethis     R (>= 3.6)
utf8        R (>= 2.10)
uuid        R (>= 2.9.0)
vctrs       R (>= 3.5.0)
viridisLite R (>= 2.10)
vroom       R (>= 3.6)
waldo       R (>= 4.0)
whisker     NA
withr       R (>= 3.6.0)
xfun        R (>= 3.2.0)
xml2        R (>= 3.6.0)
xopen       R (>= 3.1)
xtable      R (>= 2.10.0)
yaml        NA
zip         NA
base        NA
compiler    NA
datasets    NA
graphics    NA
grDevices   NA
grid        NA
methods     NA
parallel    NA
splines     NA
stats       NA
stats4      NA
tcltk       NA
tools       NA
utils       NA
            Imports
IRdisplay   methods, repr
IRkernel    repr (>= 0.4.99), methods, evaluate (>= 0.10), IRdisplay (>=\n0.3.0.9999), pbdZMQ (>= 0.2-1), crayon, jsonlite (>= 0.9.6),\nuuid, digest
pbdZMQ      NA
repr        utils, grDevices, htmltools, jsonlite, pillar (>= 1.4.0),\nbase64enc
askpass     sys (>= 2.1)
backports   NA
base64enc   NA
bit         NA
bit64       graphics, methods, stats, utils
blob        methods, rlang, vctrs (>= 0.2.1)
boot        NA
brew        NA
brio        NA
broom       backports, cli, dplyr (>= 1.0.0), generics (>= 0.0.2), glue,\nlifecycle, purrr, rlang (>= 1.1.0), stringr, tibble (>= 3.0.0),\ntidyr (>= 1.0.0)
bslib       base64enc, cachem, fastmap (>= 1.1.1), grDevices, htmltools\n(>= 0.5.8), jquerylib (>= 0.1.3), jsonlite, lifecycle, memoise\n(>= 2.0.1), mime, rlang, sass (>= 0.4.9)
cachem      rlang, fastmap (>= 1.2.0)
callr       processx (>= 3.6.1), R6, utils
cellranger  rematch, tibble
class       MASS
cli         utils
clipr       utils
cluster     graphics, grDevices, stats, utils
codetools   NA
commonmark  NA
conflicted  cli (>= 3.4.0), memoise, rlang (>= 1.0.0)
cpp11       NA
crayon      grDevices, methods, utils
credentials openssl (>= 1.3), sys (>= 2.1), curl, jsonlite, askpass
curl        NA
data.table  methods
⋮           ⋮
urlchecker  cli, curl, tools, xml2
usethis     cli (>= 3.0.1), clipr (>= 0.3.0), crayon, curl (>= 2.7), desc\n(>= 1.4.2), fs (>= 1.3.0), gert (>= 1.4.1), gh (>= 1.2.1), glue\n(>= 1.3.0), jsonlite, lifecycle (>= 1.0.0), purrr, rappdirs,\nrlang (>= 1.1.0), rprojroot (>= 1.2), rstudioapi, stats, tools,\nutils, whisker, withr (>= 2.3.0), yaml
utf8        NA
uuid        NA
vctrs       cli (>= 3.4.0), glue, lifecycle (>= 1.0.3), rlang (>= 1.1.0)
viridisLite NA
vroom       bit64, cli (>= 3.2.0), crayon, glue, hms, lifecycle (>=\n1.0.3), methods, rlang (>= 0.4.2), stats, tibble (>= 2.0.0),\ntidyselect, tzdb (>= 0.1.1), vctrs (>= 0.2.0), withr
waldo       cli, diffobj (>= 0.3.4), glue, methods, rlang (>= 1.1.0)
whisker     NA
withr       graphics, grDevices
xfun        grDevices, stats, tools
xml2        cli, methods, rlang (>= 1.1.0)
xopen       processx
xtable      stats, utils
yaml        NA
zip         NA
base        NA
compiler    NA
datasets    NA
graphics    grDevices
grDevices   NA
grid        grDevices, utils
methods     utils, stats
parallel    tools, compiler
splines     graphics, stats
stats       utils, grDevices, graphics
stats4      graphics, methods, stats
tcltk       utils
tools       NA
utils       NA
            LinkingTo
IRdisplay   NA
IRkernel    NA
pbdZMQ      NA
repr        NA
askpass     NA
backports   NA
base64enc   NA
bit         NA
bit64       NA
blob        NA
boot        NA
brew        NA
brio        NA
broom       NA
bslib       NA
cachem      NA
callr       NA
cellranger  NA
class       NA
cli         NA
clipr       NA
cluster     NA
codetools   NA
commonmark  NA
conflicted  NA
cpp11       NA
crayon      NA
credentials NA
curl        NA
data.table  NA
⋮           ⋮
urlchecker  NA
usethis     NA
utf8        NA
uuid        NA
vctrs       NA
viridisLite NA
vroom       cpp11 (>= 0.2.0), progress (>= 1.2.1), tzdb (>= 0.1.1)
waldo       NA
whisker     NA
withr       NA
xfun        NA
xml2        NA
xopen       NA
xtable      NA
yaml        NA
zip         NA
base        NA
compiler    NA
datasets    NA
graphics    NA
grDevices   NA
grid        NA
methods     NA
parallel    NA
splines     NA
stats       NA
stats4      NA
tcltk       NA
tools       NA
utils       NA
            Suggests
IRdisplay   testthat, withr
IRkernel    testthat, roxygen2
pbdZMQ      NA
repr        methods, highr, Cairo, stringr, testthat (>= 3.0.0), leaflet
askpass     testthat
backports   NA
base64enc   NA
bit         testthat (>= 3.0.0), roxygen2, knitr, markdown, rmarkdown,\nmicrobenchmark, bit64 (>= 4.0.0), ff (>= 4.0.0)
bit64       testthat (>= 3.0.3), withr
blob        covr, crayon, pillar (>= 1.2.1), testthat
boot        MASS, survival
brew        testthat (>= 3.0.0)
brio        covr, testthat (>= 3.0.0)
broom       AER, AUC, bbmle, betareg (>= 3.2-1), biglm, binGroup, boot,\nbtergm (>= 1.10.6), car (>= 3.1-2), carData, caret, cluster,\ncmprsk, coda, covr, drc, e1071, emmeans, epiR (>= 2.0.85), ergm\n(>= 3.10.4), fixest (>= 0.9.0), gam (>= 1.15), gee, geepack,\nggplot2, glmnet, glmnetUtils, gmm, Hmisc, interp, irlba,\njoineRML, Kendall, knitr, ks, Lahman, lavaan (>= 0.6.18),\nleaps, lfe, lm.beta, lme4, lmodel2, lmtest (>= 0.9.38),\nlsmeans, maps, margins, MASS, mclust, mediation, metafor, mfx,\nmgcv, mlogit, modeldata, modeltests (>= 0.1.6), muhaz,\nmultcomp, network, nnet, ordinal, plm, poLCA, psych, quantreg,\nrmarkdown, robust, robustbase, rsample, sandwich, spatialreg,\nspdep (>= 1.1), speedglm, spelling, survey, survival (>=\n3.6-4), systemfit, testthat (>= 3.0.0), tseries, vars, zoo
bslib       bsicons, curl, fontawesome, future, ggplot2, knitr, magrittr,\nrappdirs, rmarkdown (>= 2.7), shiny (> 1.8.1), testthat,\nthematic, tools, utils, withr, yaml
cachem      testthat
callr       asciicast (>= 2.3.1), cli (>= 1.1.0), mockery, ps, rprojroot,\nspelling, testthat (>= 3.2.0), withr (>= 2.3.0)
cellranger  covr, testthat (>= 1.0.0), knitr, rmarkdown
class       NA
cli         callr, covr, crayon, digest, glue (>= 1.6.0), grDevices,\nhtmltools, htmlwidgets, knitr, methods, processx, ps (>=\n1.3.4.9000), rlang (>= 1.0.2.9003), rmarkdown, rprojroot,\nrstudioapi, testthat (>= 3.2.0), tibble, whoami, withr
clipr       covr, knitr, rmarkdown, rstudioapi (>= 0.5), testthat (>=\n2.0.0)
cluster     MASS, Matrix
codetools   NA
commonmark  curl, testthat, xml2
conflicted  callr, covr, dplyr, Matrix, methods, pkgload, testthat (>=\n3.0.0), withr
cpp11       bench, brio, callr, cli, covr, decor, desc, ggplot2, glue,\nknitr, lobstr, mockery, progress, rmarkdown, scales, Rcpp,\ntestthat (>= 3.2.0), tibble, utils, vctrs, withr
crayon      mockery, rstudioapi, testthat, withr
credentials testthat, knitr, rmarkdown
curl        spelling, testthat (>= 1.0.0), knitr, jsonlite, later,\nrmarkdown, httpuv (>= 1.4.4), webutils
data.table  bit64 (>= 4.0.0), bit (>= 4.0.4), R.utils, xts, zoo (>=\n1.8-1), yaml, knitr, markdown
⋮           ⋮
urlchecker  covr
usethis     covr, knitr, magick, pkgload (>= 1.3.2.1), rmarkdown,\nroxygen2 (>= 7.1.2), spelling (>= 1.2), styler (>= 1.2.0),\ntestthat (>= 3.1.8)
utf8        cli, covr, knitr, rlang, rmarkdown, testthat (>= 3.0.0),\nwithr
uuid        NA
vctrs       bit64, covr, crayon, dplyr (>= 0.8.5), generics, knitr,\npillar (>= 1.4.4), pkgdown (>= 2.0.1), rmarkdown, testthat (>=\n3.0.0), tibble (>= 3.1.3), waldo (>= 0.2.0), withr, xml2,\nzeallot
viridisLite hexbin (>= 1.27.0), ggplot2 (>= 1.0.1), testthat, covr
vroom       archive, bench (>= 1.1.0), covr, curl, dplyr, forcats, fs,\nggplot2, knitr, patchwork, prettyunits, purrr, rmarkdown,\nrstudioapi, scales, spelling, testthat (>= 2.1.0), tidyr,\nutils, waldo, xml2
waldo       bit64, R6, S7, testthat (>= 3.0.0), withr, xml2
whisker     markdown
withr       callr, DBI, knitr, methods, rlang, rmarkdown (>= 2.12),\nRSQLite, testthat (>= 3.0.0)
xfun        testit, parallel, codetools, methods, rstudioapi, tinytex (>=\n0.30), mime, litedown (>= 0.6), commonmark, knitr (>= 1.50),\nremotes, pak, curl, xml2, jsonlite, magick, yaml, data.table,\nqs
xml2        covr, curl, httr, knitr, magrittr, mockery, rmarkdown,\ntestthat (>= 3.2.0), xslt
xopen       ps, testthat (>= 3.0.0)
xtable      knitr, plm, zoo, survival
yaml        RUnit
zip         covr, pillar, processx, R6, testthat, withr
base        methods
compiler    NA
datasets    NA
graphics    NA
grDevices   KernSmooth
grid        NA
methods     codetools
parallel    methods
splines     Matrix, methods
stats       MASS, Matrix, SuppDists, methods, stats4
stats4      NA
tcltk       NA
tools       codetools, methods, xml2, curl, commonmark, knitr, xfun, mathjaxr, V8
utils       methods, xml2, commonmark, knitr, jsonlite
            Enhances
IRdisplay   NA
IRkernel    NA
pbdZMQ      NA
repr        data.table, tibble, htmlwidgets, vegalite, plotly, geojsonio
askpass     NA
backports   NA
base64enc   png
bit         NA
bit64       NA
blob        NA
boot        NA
brew        NA
brio        NA
broom       NA
bslib       NA
cachem      NA
callr       NA
cellranger  NA
class       NA
cli         NA
clipr       NA
cluster     mvoutlier, fpc, ellipse, sfsmisc
codetools   NA
commonmark  NA
conflicted  NA
cpp11       NA
crayon      NA
credentials NA
curl        NA
data.table  NA
⋮           ⋮
urlchecker  NA
usethis     NA
utf8        NA
uuid        NA
vctrs       NA
viridisLite NA
vroom       NA
waldo       NA
whisker     NA
withr       NA
xfun        NA
xml2        NA
xopen       NA
xtable      NA
yaml        NA
zip         NA
base        chron, date, round
compiler    NA
datasets    NA
graphics    vcd
grDevices   NA
grid        NA
methods     NA
parallel    snow, Rmpi, mirai
splines     NA
stats       Kendall, coin, multcomp, pcaPP, pspearman, robustbase
stats4      NA
tcltk       NA
tools       NA
utils       NA
            License                                License_is_FOSS
IRdisplay   MIT + file LICENSE                     NA
IRkernel    MIT + file LICENSE                     NA
pbdZMQ      GPL-3                                  NA
repr        GPL (>= 3)                             NA
askpass     MIT + file LICENSE                     NA
backports   GPL-2 | GPL-3                          NA
base64enc   GPL-2 | GPL-3                          NA
bit         GPL-2 | GPL-3                          NA
bit64       GPL-2 | GPL-3                          NA
blob        MIT + file LICENSE                     NA
boot        Unlimited                              NA
brew        GPL (>= 2)                             NA
brio        MIT + file LICENSE                     NA
broom       MIT + file LICENSE                     NA
bslib       MIT + file LICENSE                     NA
cachem      MIT + file LICENSE                     NA
callr       MIT + file LICENSE                     NA
cellranger  MIT + file LICENSE                     NA
class       GPL-2 | GPL-3                          NA
cli         MIT + file LICENSE                     NA
clipr       GPL-3                                  NA
cluster     GPL (>= 2)                             NA
codetools   GPL                                    NA
commonmark  BSD_2_clause + file LICENSE            NA
conflicted  MIT + file LICENSE                     NA
cpp11       MIT + file LICENSE                     NA
crayon      MIT + file LICENSE                     NA
credentials MIT + file LICENSE                     NA
curl        MIT + file LICENSE                     NA
data.table  MPL-2.0 | file LICENSE                 NA
⋮           ⋮                                      ⋮
urlchecker  GPL-3                                  NA
usethis     MIT + file LICENSE                     NA
utf8        Apache License (== 2.0) | file LICENSE NA
uuid        MIT + file LICENSE                     NA
vctrs       MIT + file LICENSE                     NA
viridisLite MIT + file LICENSE                     NA
vroom       MIT + file LICENSE                     NA
waldo       MIT + file LICENSE                     NA
whisker     GPL-3                                  NA
withr       MIT + file LICENSE                     NA
xfun        MIT + file LICENSE                     NA
xml2        MIT + file LICENSE                     NA
xopen       MIT + file LICENSE                     NA
xtable      GPL (>= 2)                             NA
yaml        BSD_3_clause + file LICENSE            NA
zip         MIT + file LICENSE                     NA
base        Part of R 4.5.1                        NA
compiler    Part of R 4.5.1                        NA
datasets    Part of R 4.5.1                        NA
graphics    Part of R 4.5.1                        NA
grDevices   Part of R 4.5.1                        NA
grid        Part of R 4.5.1                        NA
methods     Part of R 4.5.1                        NA
parallel    Part of R 4.5.1                        NA
splines     Part of R 4.5.1                        NA
stats       Part of R 4.5.1                        NA
stats4      Part of R 4.5.1                        NA
tcltk       Part of R 4.5.1                        NA
tools       Part of R 4.5.1                        NA
utils       Part of R 4.5.1                        NA
            License_restricts_use OS_type MD5sum NeedsCompilation Built
IRdisplay   NA                    NA      NA     no               4.5.1
IRkernel    NA                    NA      NA     no               4.5.1
pbdZMQ      NA                    NA      NA     yes              4.5.1
repr        NA                    NA      NA     no               4.5.1
askpass     NA                    NA      NA     yes              4.4.0
backports   NA                    NA      NA     yes              4.4.0
base64enc   NA                    NA      NA     yes              4.0.2
bit         NA                    NA      NA     yes              4.4.0
bit64       NA                    NA      NA     yes              4.4.0
blob        NA                    NA      NA     no               4.2.0
boot        NA                    NA      NA     no               4.4.0
brew        NA                    NA      NA     no               4.3.0
brio        NA                    NA      NA     yes              4.3.0
broom       NA                    NA      NA     no               4.5.0
bslib       NA                    NA      NA     no               4.4.0
cachem      NA                    NA      NA     yes              4.4.0
callr       NA                    NA      NA     no               4.3.0
cellranger  NA                    NA      NA     no               4.0.1
class       NA                    NA      NA     yes              4.4.0
cli         NA                    NA      NA     yes              4.4.0
clipr       NA                    NA      NA     no               4.2.0
cluster     NA                    NA      NA     yes              4.4.0
codetools   NA                    NA      NA     no               4.3.0
commonmark  NA                    NA      NA     yes              4.5.0
conflicted  NA                    NA      NA     no               4.2.0
cpp11       NA                    NA      NA     no               4.4.0
crayon      NA                    NA      NA     no               4.4.0
credentials NA                    NA      NA     no               4.4.0
curl        NA                    NA      NA     yes              4.5.0

In [ ]:
c <- c("34","@34","45")
c

[1] "34"  "@34" "45"

In [ ]:
paste("this","is","r","basics", sep="   ")

[1] "this   is   r   basics"

In [ ]:
d <- c("a","b","v")
d

[1] "a" "b" "v"

In [ ]:
paste(d, collapse = " ")

[1] "a b v"

In [ ]:
a <- 1:3
b <- 1:5
c <- 1:6
a+b

Warning message in a + b:
“longer object length is not a multiple of shorter object length”

[1] 2 4 6 5 7

In [ ]:
b[c(3:4)]

[1] 3 4

In [ ]:
c[c >= 3]

[1] 3 4 5 6

In [ ]:
# loops in the R

In [ ]:
a <- c(1,3,4,5,6,NA,13,4)
for (i in 1:length(a)) {
  if (is.na(a[i])) a[i] <- 0
}
a

[1]  1  3  4  5  6  0 13  4

In [ ]:
a <- ifelse(is.na(a),0,a)
a

[1] 1 3 4 5 6

In [ ]:
# matrices

In [ ]:
x <- matrix(1:10, nrow=2, ncol=5)
y <- matrix(nrow=3, ncol=3)

In [ ]:
x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9
[2,] 2    4    6    8    10

In [ ]:
y

     [,1] [,2] [,3]
[1,] NA   NA   NA
[2,] NA   NA   NA
[3,] NA   NA   NA

In [ ]:
y <- matrix(2, nrow=2, ncol=5)
y

     [,1] [,2] [,3] [,4] [,5]
[1,] 2    2    2    2    2
[2,] 2    2    2    2    2

In [ ]:
x+y

     [,1] [,2] [,3] [,4] [,5]
[1,] 3    5    7     9   11
[2,] 4    6    8    10   12

In [ ]:
z <- t(y)

In [ ]:
z

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2
[5,] 2    2

In [ ]:
# mat multiplication
x %*% z

     [,1] [,2]
[1,] 50   50
[2,] 60   60

In [ ]:
a <- c(10,20)
a

[1] 10 20

In [ ]:
a + z

     [,1] [,2]
[1,] 12   22
[2,] 22   12
[3,] 12   22
[4,] 22   12
[5,] 12   22

In [ ]:
# list and df in R

In [ ]:
data(iris)

In [ ]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

In [ ]:
# R functions
fun1 <- function(x) {
  y <- 2/x +23
  return(y)
}

out <- fun1(3)

In [ ]:
out

[1] 23.66667

In [ ]:
out <- fun1(c(1:5))

In [ ]:
out

[1] 25.00000 24.00000 23.66667 23.50000 23.40000

In [ ]:
fun2 <- function(x) {
  re <- paste(x, "is easy", sep=" ")
  return(re)
}

x <- "writing func"
fun2(x)

[1] "writing func is easy"

In [ ]:
x2 <- c("writing func","r"," learning stat")
fun2(x2)

[1] "writing func is easy"   "r is easy"              " learning stat is easy"

In [ ]:
est <- function(x) {
  mean <- mean(x)
  var <- var(x)
  return(c(mean,var))
}

vec <- c(1:10)
out <- est(vec)
out

[1] 5.500000 9.166667

In [ ]:
# r packages

In [ ]:
library(spatial)

In [ ]:
library(help=spatial)

In [ ]:
# r help

In [ ]:
help(outer)