<a href="https://colab.research.google.com/github/avikumart/DA-DS-Questions/blob/main/R_codes/web_scraping_and_shiny_app_using_R_hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
library(rvest)
library(tidyverse)
library(lubridate)
library(xml2)

In [25]:
# scrape the covid data
url.deaths <- "https://en.wikipedia.org/wiki/COVID-19_pandemic_death_rates_by_country"

In [35]:
url.vaccines <- "https://en.wikipedia.org/wiki/COVID-19_vaccine"

In [32]:
# write the scraping function for the the both sites
page <- read_html(url.deaths)

tbl_node <- page %>%
  html_node(xpath = "//table[contains(@class, 'wikitable') and contains(., 'Deaths / million')]")

tbl <- tbl_node %>%
  html_table(fill = TRUE)

In [33]:
colnames(tbl) <- c("Country","Deaths_per_million","Deaths","Cases")

tbl_clean <- tbl %>%
  mutate(
  Deaths_per_million = as.numeric(gsub(",", "", Deaths_per_million)),
  Deaths = as.numeric(gsub(",", "", Deaths)),
  Cases = as.numeric(gsub(",", "", Cases))
  )

head(tbl_clean)

Warning message:
“There were 3 warnings in `mutate()`.
The first warning was:
ℹ In argument: `Deaths_per_million = as.numeric(gsub(",", "",
  Deaths_per_million))`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 2 remaining warnings.”

  Country                Deaths_per_million Deaths  Cases
1 World[a]                892               7101682 778602438
2 Peru                   6603                221060   4532724
3 Bulgaria               5679                 38767   1339176
4 North Macedonia        5429                  9991    352093
5 Bosnia and Herzegovina 5119                 16406    404289
6 Hungary                5072                 49124   2238461

In [34]:
tbl_clean

    Country
1   World[a]
2   Peru
3   Bulgaria
4   North Macedonia
5   Bosnia and Herzegovina
6   Hungary
7   Croatia
8   Slovenia
9   Georgia
10  Montenegro
11  Czech Republic
12  Latvia
13  Moldova
14  Slovakia
15  Greece
16  San Marino
17  Romania
18  United States
19  Lithuania
20  United Kingdom
21  Brazil
22  Italy
23  Chile
24  Martinique
25  Poland
26  Armenia
27  Gibraltar
28  Belgium
29  Paraguay
30  Trinidad and Tobago
⋮   ⋮
211 Ghana
212 Nicaragua
213 Guinea
214 Mali
215 Togo
216 Eritrea
217 Uzbekistan
218 Ivory Coast
219 Bhutan
220 Central African Republic
221 Burkina Faso
222 Sierra Leone
223 Democratic Republic of the Congo
224 Nigeria
225 South Sudan
226 Tanzania
227 Niger
228 Tajikistan
229 Benin
230 Chad
231 Burundi
232 Vatican City
233 Niue
234 Falkland Islands
235 Saint Helena, Ascension and Tristan da Cunha
236 Pitcairn Islands
237 Tokelau
238 North Korea
239 Turkmenistan
240 .mw-parser-output .reflist{margin-bottom:0.5em;list-style-type:decimal}@media screen{.mw-parser-output .reflist{font-size:90%}}.mw-parser-output .reflist .references{font-size:100%;margin-bottom:0;list-style-type:inherit}.mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}.mw-parser-output .reflist-columns{margin-top:0.3em}.mw-parser-output .reflist-columns ol{margin-top:0}.mw-parser-output .reflist-columns li{page-break-inside:avoid;break-inside:avoid-column}.mw-parser-output .reflist-upper-alpha{list-style-type:upper-alpha}.mw-parser-output .reflist-upper-roman{list-style-type:upper-roman}.mw-parser-output .reflist-lower-alpha{list-style-type:lower-alpha}.mw-parser-output .reflist-lower-greek{list-style-type:lower-greek}.mw-parser-output .reflist-lower-roman{list-style-type:lower-roman}\n^ Countries which do not report data for a column are not included in that column's world total.\n\n^ Data on member states of the European Union are individually listed, but are also summed here for convenience. They are not double-counted in world totals.\n\n^ Does not include special administrative regions (Hong Kong and Macau) or Taiwan.
    Deaths_per_million Deaths  Cases
1    892               7101682 778602438
2   6603                221060   4532724
3   5679                 38767   1339176
4   5429                  9991    352093
5   5119                 16406    404289
6   5072                 49124   2238461
7   4807                 18784   1360993
8   4686                  9914   1363849
9   4519                 17151   1864386
10  4317                  2654    251280
11  4107                 43842   4845268
12  4059                  7636    977783
13  4042                 12289    656072
14  3888                 21282   1886598
15  3851                 40108   5804824
16  3693                   126     25292
17  3601                 69027   3593509
18  3596               1228289 103436829
19  3508                  9884   1438441
20  3404                232112  25075478
21  3344                703283  37823149
22  3329                198523  26968605
23  3298                 64497   5410188
24  3159                  1104    230354
25  3151                120979   6799334
26  3049                  8785    454686
27  3002                   113     20550
28  2949                 34339   4899781
29  2940                 19880    735759
30  2934                  4390    191496
⋮   ⋮                  ⋮       ⋮
211 44                 1463    172750
212 36                  245     16398
213 33                  468     38593
214 32                  743     33197
215 31                  290     39553
216 30                  103     10189
217 29                 1016    175132
218 27                  835     88434
219 26                   21     63191
220 22                  113     15486
221 17                  400     22216
222 15                  126      7985
223 14                 1474    101010
224 14                 3155    267227
225 13                  147     18873
226 13                  846     43600
227 12                  315      9573
228 12                  125     17786
229 11                  163     28036
230 10                  194      7702
231  1                   15     54569
232  0                    0        26
233  0                    0      1092
234  0                    0      1923
235  0                    0      2166
236  0                    0         4
237  0                    0        80
238  0                    0         0
239  0                    0         0
240 NA                   NA        NA

In [36]:
# scrape the data for the vaccines data
page1 <- read_html(url.vaccines)

tbl_node1 <- page1 %>%
  html_node(xpath = '//*[@id="mw-content-text"]/div[1]/table[4]')

tbl1 <- tbl_node1 %>%
  html_table(fill = TRUE)

In [37]:
head(tbl1)

  Common name
1 Authorized in more than 10 countries and by the WHO
2 Oxford–AstraZeneca
3 Pfizer–BioNTech
4 Janssen (Johnson & Johnson)
5 Moderna
6 Sinopharm BIBP
  Type (technology)
1 Authorized in more than 10 countries and by the WHO
2 Adenovirus vector
3 RNA
4 Adenovirus vector
5 RNA
6 Inactivated
  Country of origin
1 Authorized in more than 10 countries and by the WHO
2 United Kingdom,Sweden
3 Germany,United States
4 United States,Netherlands
5 United States
6 China
  First authorization
1 Authorized in more than 10 countries and by the WHO
2 December 2020
3 December 2020
4 February 2021
5 December 2020
6 July 2020
  Notes
1 Authorized in more than 10 countries and by the WHO
2
3 Both original and Omicron variant versions
4
5 Both original and Omicron variant versions
6

In [38]:
# map visualization of death rates by each country
install.packages(c("rvest", "dplyr", "rnaturalearth",
                   "rnaturalearthdata", "sf", "ggplot2"))

library(rvest)
library(dplyr)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘proxy’, ‘e1071’, ‘wk’, ‘terra’, ‘classInt’, ‘s2’, ‘units’



Attaching package: ‘rnaturalearthdata’


The following object is masked from ‘package:rnaturalearth’:

    countries110


Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.3.1; sf_use_s2() is TRUE

In [39]:
world <- ne_countries(scale = "medium", returnclass = "sf")

In [42]:
tbl_clean <- tbl_clean %>%
  rename("sovereignt" = "Country")

In [44]:
world_data <- left_join(world, tbl_clean, by = c("name" = "sovereignt"))

## Shiny practice app

In [20]:
ui <- fluidPage(

  # App title ----
  titlePanel("Tabsets"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Select the random distribution type ----
      radioButtons("dist", "Distribution type:",
                   c("Normal" = "norm",
                     "Uniform" = "unif",
                     "Log-normal" = "lnorm",
                     "Exponential" = "exp")),

      # Input: Slider for the number of observations to generate ----
      sliderInput("n",
                  "Number of observations:",
                  value = 500,
                  min = 1,
                  max = 1000)

    ),

    # Main panel for displaying outputs ----
    mainPanel(plotOutput("plot"))
  )
)

# Define server logic for random distribution app ----
server <- function(input, output) {

  # Generate a plot of the data ----
  # Also uses the inputs to build the plot label. Note that all expressions are called in the sequence
  # implied by the dependency graph.
   output$plot <- renderPlot({
    n <- input$n
    dist <- switch(input$dist,
                   norm = rnorm,
                   unif = runif,
                   lnorm = rlnorm,
                   exp = rexp,
                   rnorm)

    hist(dist(input$n), main="Histogram")
  })
}

# Create Shiny app ----
shinyApp(ui, server)

ERROR: Error in fluidPage(titlePanel("Tabsets"), sidebarLayout(sidebarPanel(radioButtons("dist", : could not find function "fluidPage"