<a href="https://colab.research.google.com/github/avikumart/DA-DS-Questions/blob/main/R_codes/web_scraping_in_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# install libs
library(tidyverse)
library(readr)
library(dplyr)
library(rvest)
library(xml2)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘rvest’


The following object is masked from ‘package:readr’:

    guess_encoding

In [2]:
# take covid url for the web scraping
covid.url <- 'https://www.worldometers.info/coronavirus/#countries'

In [11]:
# get the xpath
xpath.country <- '//*[@id="main_table_countries_today"]'

In [13]:
# scrap the data using above details
covid.dt <- covid.url %>%
  read_html() %>%
  html_nodes(xpath=xpath.country) %>%
  html_table(header=TRUE) %>%
  .[[1]] %>%
  filter(!is.na(`#`))
head(covid.dt, 10)

   #  Country,Other TotalCases  NewCases TotalDeaths NewDeaths TotalRecovered
1   1 USA           111,820,082 NA       1,219,487   NA        109,814,428
2   2 India         45,035,393  NA       533,570     NA        N/A
3   3 France        40,138,560  NA       167,642     NA        39,970,918
4   4 Germany       38,828,995  NA       183,027     NA        38,240,600
5   5 Brazil        38,743,918  NA       711,380     NA        36,249,161
6   6 S. Korea      34,571,873  NA       35,934      NA        34,535,939
7   7 Japan         33,803,572  NA       74,694      NA        N/A
8   8 Italy         26,723,249  NA       196,487     NA        26,361,218
9   9 UK            24,910,387  NA       232,112     NA        24,678,275
10 10 Russia        24,124,215  NA       402,756     NA        23,545,818
   NewRecovered ActiveCases Serious,Critical ⋯ TotalTests    Tests/1M pop
1               786,167     940              ⋯ 1,186,851,502 3,544,901
2  N/A          N/A         N/A              ⋯ 935,879,495   665,334
3               0                            ⋯ 271,490,188   4,139,547
4               405,368     N/A              ⋯ 122,332,384   1,458,359
5               1,783,377   N/A              ⋯ 63,776,166    296,146
6               0                            ⋯ 15,804,065    307,892
7  N/A          N/A         N/A              ⋯ 100,414,883   799,578
8               165,544     22               ⋯ 281,126,449   4,665,010
9               0           N/A              ⋯ 522,526,476   7,628,357
10              175,641     N/A              ⋯ 273,400,000   1,875,095
   Population    Continent     1 Caseevery X ppl 1 Deathevery X ppl
1  334,805,269   North America 3                 275
2  1,406,631,776 Asia          31                2,636
3  65,584,518    Europe        2                 391
4  83,883,596    Europe        2                 458
5  215,353,593   South America 6                 303
6  51,329,899    Asia          1                 1,428
7  125,584,838   Asia          4                 1,681
8  60,262,770    Europe        2                 307
9  68,497,907    Europe        3                 295
10 145,805,947   Europe        6                 362
   1 Testevery X ppl New Cases/1M pop New Deaths/1M pop Active Cases/1M pop
1  0                 NA               NA                2,348
2  2                 NA               NA                0.4
3  0                 NA               NA
4  1                 NA               NA                4,833
5  3                 NA               NA                8,281
6  3                 NA               NA
7  1                 NA               NA                95,582
8  0                 NA               NA                2,747
9  0                 NA               NA
10 1                 NA               NA                1,205

In [15]:
covid.dt

    #   Country,Other          TotalCases  NewCases TotalDeaths NewDeaths
1    1  USA                    111,820,082 NA       1,219,487   NA
2    2  India                  45,035,393  NA       533,570     NA
3    3  France                 40,138,560  NA       167,642     NA
4    4  Germany                38,828,995  NA       183,027     NA
5    5  Brazil                 38,743,918  NA       711,380     NA
6    6  S. Korea               34,571,873  NA       35,934      NA
7    7  Japan                  33,803,572  NA       74,694      NA
8    8  Italy                  26,723,249  NA       196,487     NA
9    9  UK                     24,910,387  NA       232,112     NA
10  10  Russia                 24,124,215  NA       402,756     NA
11  11  Turkey                 17,232,066  NA       102,174     NA
12  12  Spain                  13,914,811  NA       121,760     NA
13  13  Australia              11,853,144  NA       24,414      NA
14  14  Vietnam                11,625,195  NA       43,206      NA
15  15  Taiwan                 10,241,523  NA       19,005      NA
16  16  Argentina              10,128,845  NA       130,841     NA
17  17  Netherlands            8,635,786   NA       22,992      NA
18  18  Mexico                 7,702,809   NA       334,958     NA
19  19  Iran                   7,627,186   NA       146,811     NA
20  20  Indonesia              6,829,221   NA       162,063     NA
21  21  Poland                 6,661,991   NA       120,598     NA
22  22  Colombia               6,400,173   NA       143,200     NA
23  23  Greece                 6,101,379   NA       37,869      NA
24  24  Austria                6,081,287   NA       22,542      NA
25  25  Portugal               5,643,062   NA       28,126      NA
26  26  Ukraine                5,557,995   NA       112,418     NA
27  27  Chile                  5,384,853   NA       64,497      NA
28  28  Malaysia               5,278,406   NA       37,348      NA
29  29  Canada                 4,946,090   NA       59,034      NA
30  30  Belgium                4,861,695   NA       34,376      NA
⋮   ⋮   ⋮                      ⋮           ⋮        ⋮           ⋮
202 202 St. Vincent Grenadines 9,674       NA       124         NA
203 203 Guinea-Bissau          9,614       NA       177         NA
204 204 Comoros                9,109       NA       161         NA
205 205 Antigua and Barbuda    9,106       NA       146         NA
206 206 Liberia                8,090       NA       295         NA
207 207 Sierra Leone           7,779       NA       126         NA
208 208 Chad                   7,701       NA       194         NA
209 209 British Virgin Islands 7,392       NA       64          NA
210 210 Cook Islands           7,203       NA       2           NA
211 211 Sao Tome and Principe  6,778       NA       80          NA
212 212 Turks and Caicos       6,752       NA       40          NA
213 213 Saint Kitts and Nevis  6,607       NA       48          NA
214 214 Palau                  6,290       NA       10          NA
215 215 St. Barth              5,507       NA       6           NA
216 216 Nauru                  5,393       NA       1           NA
217 217 Kiribati               5,085       NA       24          NA
218 218 Anguilla               3,904       NA       12          NA
219 219 Wallis and Futuna      3,550       NA       8           NA
220 220 Saint Pierre Miquelon  3,452       NA       2           NA
221 221 Tuvalu                 2,943       NA       1           NA
222 222 Saint Helena           2,166       NA                   NA
223 223 Falkland Islands       1,930       NA                   NA
224 224 Montserrat             1,403       NA       8           NA
225 225 Niue                   1,059       NA                   NA
226 226 Diamond Princess       712         NA       13          NA
227 227 Tokelau                80          NA                   NA
228 228 Vatican City           29          NA                   NA
229 229 Western Sahara         10          NA       1           NA
230 230 MS Zaandam             9           NA       2           NA
231 231 China                  503,302     NA       5,272       NA
    TotalRecovered NewRecovered ActiveCases Serious,Critical ⋯ TotalTests
1   109,814,428                 786,167     940              ⋯ 1,186,851,502
2   N/A            N/A          N/A         N/A              ⋯ 935,879,495
3   39,970,918                  0                            ⋯ 271,490,188
4   38,240,600                  405,368     N/A              ⋯ 122,332,384
5   36,249,161                  1,783,377   N/A              ⋯ 63,776,166
6   34,535,939                  0                            ⋯ 15,804,065
7   N/A            N/A          N/A         N/A              ⋯ 100,414,883
8   26,361,218                  165,544     22               ⋯ 281,126,449
9   24,678,275                  0           N/A              ⋯ 522,526,476
10  23,545,818                  175,641     N/A              ⋯ 273,400,000
11  N/A            N/A          N/A         N/A              ⋯ 162,743,369
12  13,762,417                  30,634      231              ⋯ 471,036,328
13  11,820,014                  8,716       3                ⋯ 81,916,639
14  10,640,971                  941,018                      ⋯ 85,826,548
15  10,222,518                  0                            ⋯ 30,742,304
16  9,997,258                   746                          ⋯ 35,716,069
17  8,612,599                   195         N/A              ⋯ 25,984,435
18  6,899,865                   467,986     N/A              ⋯ 20,013,810
19  N/A            N/A          N/A                          ⋯ 57,320,267
20  6,647,104                   20,054      N/A              ⋯ 114,158,919
21  N/A            N/A          N/A         N/A              ⋯ 39,323,709
22  6,212,152                   44,821      342              ⋯ 36,951,507
23  N/A            N/A          N/A                          ⋯ 102,228,365
24  6,054,934                   3,811                        ⋯ 211,273,524
25  5,614,809                   127         61               ⋯ 46,139,518
26  5,445,577                   0                            ⋯ 32,603,805
27  5,252,450                   67,906      7                ⋯ 50,382,097
28  5,233,268                   7,790       11               ⋯ 68,580,916
29  4,881,312      +350         5,744       99               ⋯ 66,572,774
30  4,826,798      +50          521         N/A              ⋯ 37,454,182
⋮   ⋮              ⋮            ⋮           ⋮                ⋱ ⋮
202 9,493                       57                           ⋯ 114,197
203 8,929                       508         6                ⋯ 145,231
204 8,939                       9                            ⋯
205 8,954                       6           N/A              ⋯ 18,901
206 7,783                       12          2                ⋯ 139,824
207 N/A            N/A          N/A                          ⋯ 259,958
208 4,874                       2,633                        ⋯ 191,341
209 N/A            N/A          N/A                          ⋯ 107,339
210 7,150                       51                           ⋯ 19,690
211 6,685                       13                           ⋯ 29,600
212 6,709                       3           4                ⋯ 616,788
213 6,559                       0                            ⋯ 126,958
214 6,276                       4                            ⋯ 71,434
215 N/A            N/A          N/A                          ⋯ 78,646
216 5,347                       45                           ⋯ 20,509
217 2,703                       2,358       3                ⋯
218 N/A            N/A          N/A         N/A              ⋯ 51,382
219 438                         3,104                        ⋯ 20,508
220 2,449                       1,001                        ⋯ 25,400
221 N/A            N/A          N/A         N/A              ⋯
222 2                           2,164                        ⋯
223 1,930                       0                            ⋯ 8,632
224 1,376                       19                           ⋯ 17,762
225 1,056                       3                            ⋯
226 699                         0                            ⋯
227                             80                           ⋯
228 29                          0                            ⋯
229 9                           0                            ⋯
230 7                           0                            ⋯
231 379,053                     118,977     N/A              ⋯ 160,000,000
    Tests/1M pop Population    Continent         1 Caseevery X ppl
1   3,544,901    334,805,269   North America     3
2   665,334      1,406,631,776 Asia              31
3   4,139,547    65,584,518    Europe            2
4   1,458,359    83,883,596    Europe            2
5   296,146      215,353,593   South America     6
6   307,892      51,329,899    Asia              1
7   799,578      125,584,838   Asia              4
8   4,665,010    60,262,770    Europe            2
9   7,628,357    68,497,907    Europe            3
10  1,875,095    145,805,947   Europe            6
11  1,902,052    85,561,976    Asia              5
12  10,082,298   46,719,142    Europe            3
13  3,142,326    26,068,792    Australia/Oceania 2
14  867,342      98,953,541    Asia              9
15  1,286,903    23,888,595    Asia              2
16  776,264      46,010,234    South America     5
17  1,509,718    17,211,447    Europe            2
18  152,124      131,562,772   North America     17
19  666,338      86,022,837    Asia              11
20  408,975      279,134,505   Asia              41
21  1,041,970    37,739,785    Europe            6
22  717,327      51,512,762    South America     8
23  9,909,078    10,316,637    Europe            2
24  23,302,116   9,066,710     Europe            1
25  4,549,993    10,140,570    Europe            2
26  754,855      43,192,122    Europe            8
27  2,617,225    19,250,195    South America     4
28  2,066,869    33,181,072    Asia              6
29  1,734,189    38,388,419    North America     8
30  3,209,915    11,668,278    Europe            2
⋮   ⋮            ⋮             ⋮                 ⋮
202 1,023,720    111,551       North America     12
203 70,385       2,063,367     Africa            215
204              907,419       Africa            100
205 189,943      99,509        North America     11
206 26,356       5,305,117     Africa            656
207 31,296       8,306,436     Africa            1,068
208 10,988       17,413,580    Africa            2,261
209 3,508,269    30,596        North America     4
210 1,120,596    17,571        Australia/Oceania 2
211 130,008      227,679       Africa            34
212 15,520,193   39,741        North America     6
213 2,356,704    53,871        North America     8
214 3,917,841    18,233        Australia/Oceania 3
215 7,908,095    9,945         North America     2
216 1,881,042    10,903        Australia/Oceania 2
217              123,419       Australia/Oceania 24
218 3,373,736    15,230        North America     4
219 1,867,419    10,982        Australia/Oceania 3
220 4,410,488    5,759         North America     2
221              12,066        Australia/Oceania 4
222              6,115         Africa            3
223 2,439,107    3,539         South America     2
224 3,577,442    4,965         North America     4
225              1,622         Australia/Oceania 2
226
227              1,378         Australia/Oceania 17
228              799           Europe            28
229              626,161       Africa            62,616
230
231 110,461      1,448,471,400 Asia              2,878
    1 Deathevery X ppl 1 Testevery X ppl New Cases/1M pop New Deaths/1M pop
1   275                0                 NA               NA
2   2,636              2                 NA               NA
3   391                0                 NA               NA
4   458                1                 NA               NA
5   303                3                 NA               NA
6   1,428              3                 NA               NA
7   1,681              1                 NA               NA
8   307                0                 NA               NA
9   295                0                 NA               NA
10  362                1                 NA               NA
11  837                1                 NA               NA
12  384                0                 NA               NA
13  1,068              0                 NA               NA
14  2,290              1                 NA               NA
15  1,257              1                 NA               NA
16  352                1                 NA               NA
17  749                1                 NA               NA
18  393                7                 NA               NA
19  586                2                 NA               NA
20  1,722              2                 NA               NA
21  313                1                 NA               NA
22  360                1                 NA               NA
23  272                0                 NA               NA
24  402                0                 NA               NA
25  361                0                 NA               NA
26  384                1                 NA               NA
27  298                0                 NA               NA
28  888                0                 NA               NA
29  650                1                 NA               NA
30  339                0                 NA               NA
⋮   ⋮                  ⋮                 ⋮                ⋮
202 900                 1                NA               NA
203 11,657             14                NA               NA
204 5,636              NA                NA               NA
205 682                 5                NA               NA
206 17,983             38                NA               NA
207 65,924             32                NA               NA
208 89,761             91                NA               NA
209 478                 0                NA               NA
210 8,786               1                NA               NA
211 2,846               8                NA               NA
212 994                 0                NA               NA
213 1,122               0                NA               NA
214 1,823               0                NA               NA
215 1,658               0                NA               NA
216 10,903              1                NA               NA
217 5,142              NA                NA               NA
218 1,269               0                NA               NA
219 1,373               1                NA               NA
220 2,880               0                NA               NA
221 12,066             NA                NA               NA
222                    NA                NA               NA
223                     0                NA               NA
224 621                 0                NA               NA
225                    NA                NA               NA
226                    NA                NA               NA
227                    NA                NA               NA
228                    NA                NA               NA
229 626,161            NA                NA               NA
230                    NA                NA               NA
231 274,748             9                NA               NA
    Active Cases/1M pop
1   2,348
2   0.4
3
4   4,833
5   8,281
6
7   95,582
8   2,747
9
10  1,205
11  4,024
12  656
13  334
14  9,510
15
16  16
17  11
18  3,557
19  1,199
20  72
21  31,941
22  870
23
24  420
25  13
26
27  3,528
28  235
29  150
30  45
⋮   ⋮
202 511
203 246
204 10
205 60
206 2
207 332
208 151
209 3,236
210 2,903
211 57
212 75
213
214 219
215 506,687
216 4,127
217 19,106
218 854
219 282,644
220 173,815
221 243,826
222 353,884
223
224 3,827
225 1,850
226
227 58,055
228
229
230
231 82

## Goodreads install

In [16]:
# good reads url
goodreads.url <- "https://www.goodreads.com/list/show/191616"

In [17]:
# xpath of the goodreads
xpath.goodreads <- '//*[@id="bodycontainer"]'

In [19]:
# scrap the data using the rvest web scraping
good.data <- goodreads.url %>%
  read_html() %>%
  html_nodes(xpath=xpath.goodreads) %>%
  html_table()
good.data

[[1]]
# A tibble: 100 × 4
      X1 X2    X3                                                          X4
   <int> <lgl> <chr>                                                       <chr>
 1     1 NA    "Project Hail Mary\n      by\n\n\nAndy Weir (Goodreads Aut… "Wan…
 2     2 NA    "The Nightingale\n      by\n\n\nKristin Hannah (Goodreads … "Wan…
 3     3 NA    "Educated\n      by\n\n\nTara Westover (Goodreads Author)\… "Wan…
 4     4 NA    "The Women\n      by\n\n\nKristin Hannah (Goodreads Author… "Wan…
 5     5 NA    "The Complete Maus\n      by\n\n\nArt Spiegelman\n\n\n\n  … "Wan…
 6     6 NA    "The Help\n      by\n\n\nKathryn Stockett (Goodreads Autho… "Wan…
 7     7 NA    "The Heart's Invisible Furies\n      by\n\n\nJohn Boyne (G… "Wan…
 8     8 NA    "A Thousand Splendid Suns\n      by\n\n\nKhaled Hosseini (… "Wan…
 9     9 NA    "Know My Name\n      by\n\n\nChanel Miller\n\n\n\n        … "Wan…
10    10 NA    "Just Mercy\n      by\n\n\nBryan Stevenson\n\n\n\n        … "Wan…
# ℹ 90 more rows